# -*- coding: utf-8 -*-
"""Exercise2-Question.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/lmoroney/dlaicourse/blob/master/Exercises/Exercise%202%20-%20Handwriting%20Recognition/Exercise2-Question.ipynb

## Exercise 2
In the course you learned how to do classification using Fashion MNIST, a data set containing items of clothing. There's another, similar dataset called MNIST which has items of handwriting -- the digits 0 through 9.

Write an MNIST classifier that trains to 99% accuracy or above, and does it without a fixed number of epochs -- i.e. you should stop training once you reach that level of accuracy.

Some notes:
1. It should succeed in less than 10 epochs, so it is okay to change epochs to 10, but nothing larger
2. When it reaches 99% or greater it should print out the string "Reached 99% accuracy so cancelling training!"
3. If you add any additional variables, make sure you use the same names as the ones used in the class

I've started the code for you below -- how would you finish it?
"""

import tensorflow as tf
mnist = tf.keras.datasets.mnist

# define callback function
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if (logs.get("acc")>0.99):
      print("\nReached 99% accuracy so cancelling training!\n")
      self.model.stop_training=True


# instantiate callback
callbacks=myCallback()

(x_train, y_train),(x_test, y_test) = mnist.load_data()
# x_train and x_test store the images
# y_train and y_test store the labels

# showing a sample image in dataset
import matplotlib.pyplot as plt
plt.imshow(x_train[55])
print(y_train[55])
print(x_train[55])

# normalize images
x_train = x_train/255.0
x_test = x_test/255.0
      
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=10, callbacks=[callbacks])

classifications = model.predict(x_test)
print(classifications[0])

plt.imshow(x_test[0])
print(y_test[0])
print(x_test[0])